# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#     _____ _           _ _                                     #
#    / ____| |         | | |                                    #
#   | |    | |__   __ _| | | ___ _ __   __ _  ___  ___          #
#   | |    | '_ \ / _` | | |/ _ \ '_ \ / _` |/ _ \/ __|         #
#   | |____| | | | (_| | | |  __/ | | | (_| |  __/\__ \         #
#    \_____|_| |_|\__,_|_|_|\___|_| |_|\__, |\___||___/         #
#                                       __/ |                   #
#                                      |___/                    #
#                                                               #
#                                                               #
# This plugin was made by the CodingArea team                   #
# * anweisen | Angelo - https://github.com/anweisen             #
# * KxmischesDomi | Dominik - https://github.com/KxmischesDomi  #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

config-version: 1.1.3
# Most recent config changes: (v1.1.3)
# - Moved prefix settings to messages/prefix.properties
# - drop-inventory-on-end setting added

# This language will only be used for messages which are not set in the messages.properties
# and for the descriptions of the challenges in the menu
# Available languages:
# en (english)
# de (german)
language: 'en'

# Timer design above the hotbar
# (tags) %time%
timer-up: '§8• §7Time: §a§l%time% §8•'
timer-down: '§8• §7Time: §c§l%time% §8•'
timer-stopped: '§8• §7Timer §c§lstopped §8•'

# This is the backpack size, its counting in 9slot rows
# (i) The max count of rows is 6
backpack-size: 3

# These message will be shown when somebody leaves/joins the server
# (tags) %player% -> The player's name, %display% -> The player's display name
connection-messages-enabled: true
join-message: '§8§l┃ §6Challenges §8┃ §e%display% §ajoined §7the server'
quit-message: '§8§l┃ §6Challenges §8┃ §e%display% §cleft §7the server'

chatformat-enabled: true
chatformat: '§8§l┃ §7%display%%name% §8»§7 %message%'

# Toggles if the players inventories will be dropped on their positions if either they win or lose
drop-inventory-on-end: true

# If you enable this the start command defined in the spigot.yml will be executed
# Otherwise the server will only be stopped if the reset command was executed
# Please note: We are getting a lot of reports that the server is not restarting after the /reset command was executed.
# So make sure that the server restarts when you perform the /restart command before reporting it to us!
restart-on-reset: true

# This means that you you have to type /reset confirm to reset your server/worlds
force-reset-confirm: true

# This will reset the world and restart the server, when the last person leaves the server and the timer was already started at one time
reset-on-last-quit: false
disable-whitelist-on-start: true

# This will set the gamestate of a server to ingame when the timer starts.
# It will also start a new server (if enabled) if the timer was started for the first time
# (i) Only available for the cloudnet version 3.3.0-RELEASE
cloudnet-support: false
start-new-server: true

# You need a mysql connection to save the player configs or stats
save-player-configs: false
save-player-stats: false

# This is only needed if you want to save player configs or player stats
mysql:
  enabled: false
  host: '127.0.0.1:3306'
  database: 'challenges'
  user: 'root'
  password: 'secret'
